Pipe: Added check in PipeSubtask submit logic to ensure one PipeConnectorSubtask instance is running in only one thread (#11474)
If the last subtask is running when the subtask is stopped and started again, the subtask will be submitted by the start process and itself when it finishes last round, causing concurrent problems like this:

o.a.t.a.TAsyncClientManager$SelectThread:117 - Ignoring uncaught exception in SelectThread
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
at java.base/java.util.Objects.checkIndex(Objects.java:372)
at java.base/java.util.ArrayList.get(ArrayList.java:459)
at org.apache.iotdb.db.pipe.connector.protocol.thrift.async.handler.PipeTransferTabletBatchEventHandler.onError(PipeTransferTabletBatchEventHandler.java:95)
at org.apache.thrift.async.TAsyncMethodCall.onError(TAsyncMethodCall.java:216)
at org.apache.thrift.async.TAsyncMethodCall.transition(TAsyncMethodCall.java:210)
at org.apache.thrift.async.TAsyncClientManager$SelectThread.transitionMethods(TAsyncClientManager.java:143)
at org.apache.thrift.async.TAsyncClientManager$SelectThread.run(TAsyncClientManager.java:113)

This is because two threads share the same batch builder in async connector, and one is using the copy of its elements to create handler while one is adding elements to the batch, resulting to elements number inequality in handler due to some unadded elements in batch builder.

This commit solved the problem and allow only 1 thread to pick the subtask.

---------

Co-authored-by: Steve Yurong Su <rong@apache.org>