Pipe: preliminary SSL support for pipe connector (sink) sync client (#11465)
THIS commit is a follow-up in Pipe for https://github.com/apache/iotdb/pull/11218.

When using iotdb-thrift-sync-connector and iotdb-legacy-pipe-connector, now can configure the sender-side SSL related settings in parameters.

| Key                      | Value                                                        | Value Range       | Required or Optional with Default |
| ------------------------ | ------------------------------------------------------------ | ----------------- | --------------------------------- |
| sink.ssl.enable          | Whether the data service of one of the DN in the target IoTDB supports SSL. | Boolean: true, false | Optional: Default is false         |
| sink.ssl.trust-store-path | The path to the certificate of the Trust Store required for SSL when connecting to the data service of one of the DN in the target IoTDB. | String            | Optional: Required if sink.ssl.enable is true |
| sink.ssl.trust-store-pwd  | The password for the certificate of the Trust Store required for SSL when connecting to the data service of one of the DN in the target IoTDB. | String            | Optional: Required if sink.ssl.enable is true |

For example:

```sql
create pipe a2b
with connector (
    'connector'='iotdb-thrift-sync-connector',
    'sink.ip'='127.0.0.1',
    'sink.port'='6668',
    'sink.ssl.enable'='true',
    'sink.ssl.trust-store-path'='/home/vgalaxy/.truststore',
    'sink.ssl.trust-store-pwd'='123456',
);
```

If the Pipe receiver is configured with SSL, but the sender is not, the sender will throw an error.

```text
2023-11-02 20:54:53,300 [pool-30-IoTDB-DataNodeInternalRPC-Processor-2] WARN  o.a.i.d.p.a.t.PipeTaskAgent:216 - Failed to handle pipe meta changes for a2b 
org.apache.iotdb.pipe.api.exception.PipeException: Failed to construct PipeConnector, because of All target servers [TEndPoint(ip:127.0.0.1, port:6668)] are not available.
        at org.apache.iotdb.db.pipe.task.subtask.connector.PipeConnectorSubtaskManager.register(PipeConnectorSubtaskManager.java:105)
        at org.apache.iotdb.db.pipe.task.stage.PipeTaskConnectorStage.<init>(PipeTaskConnectorStage.java:42)
        at org.apache.iotdb.db.pipe.task.PipeTaskBuilder.build(PipeTaskBuilder.java:58)
        at org.apache.iotdb.db.pipe.agent.task.PipeTaskAgent.createPipeTask(PipeTaskAgent.java:827)
        at org.apache.iotdb.db.pipe.agent.task.PipeTaskAgent.executeSinglePipeRuntimeMetaChanges(PipeTaskAgent.java:301)
        at org.apache.iotdb.db.pipe.agent.task.PipeTaskAgent.executeSinglePipeMetaChanges(PipeTaskAgent.java:275)
        at org.apache.iotdb.db.pipe.agent.task.PipeTaskAgent.handlePipeMetaChangesInternal(PipeTaskAgent.java:210)
        at org.apache.iotdb.db.pipe.agent.task.PipeTaskAgent.handlePipeMetaChanges(PipeTaskAgent.java:191)
        at org.apache.iotdb.db.protocol.thrift.impl.DataNodeInternalRPCServiceImpl.pushPipeMeta(DataNodeInternalRPCServiceImpl.java:943)
        at org.apache.iotdb.mpp.rpc.thrift.IDataNodeRPCService$Processor$pushPipeMeta.getResult(IDataNodeRPCService.java:5746)
        at org.apache.iotdb.mpp.rpc.thrift.IDataNodeRPCService$Processor$pushPipeMeta.getResult(IDataNodeRPCService.java:5726)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.iotdb.pipe.api.exception.PipeConnectionException: All target servers [TEndPoint(ip:127.0.0.1, port:6668)] are not available.
        at org.apache.iotdb.db.pipe.connector.protocol.thrift.sync.IoTDBThriftSyncConnector.handshake(IoTDBThriftSyncConnector.java:211)
        at org.apache.iotdb.db.pipe.task.subtask.connector.PipeConnectorSubtaskManager.register(PipeConnectorSubtaskManager.java:102)
        ... 16 common frames omitted
```

**Known limitations:**

1. For all `nodeUrls` (`sink.ip:sink.port` ∪ `sink.node-urls`), their SSL configuration is shared.
2. Due to the fact that Thrift does not natively support SSL for async clients, it's not ready to configure SSL in iotdb-thrift-async-connector (iotdb-thrift-connector). Doing so will result in an error.

```text
2023-11-02 20:43:32,837 [pool-30-IoTDB-DataNodeInternalRPC-Processor-2] WARN  o.a.i.d.p.a.t.PipeTaskAgent:216 - Failed to handle pipe meta changes for a2b 
org.apache.iotdb.pipe.api.exception.PipeException: Failed to construct PipeConnector, because of IoTDBThriftAsyncConnector does not support SSL transmission currently
        at org.apache.iotdb.db.pipe.task.subtask.connector.PipeConnectorSubtaskManager.register(PipeConnectorSubtaskManager.java:105)
        at org.apache.iotdb.db.pipe.task.stage.PipeTaskConnectorStage.<init>(PipeTaskConnectorStage.java:42)
        at org.apache.iotdb.db.pipe.task.PipeTaskBuilder.build(PipeTaskBuilder.java:58)
        at org.apache.iotdb.db.pipe.agent.task.PipeTaskAgent.createPipeTask(PipeTaskAgent.java:827)
        at org.apache.iotdb.db.pipe.agent.task.PipeTaskAgent.executeSinglePipeRuntimeMetaChanges(PipeTaskAgent.java:301)
        at org.apache.iotdb.db.pipe.agent.task.PipeTaskAgent.executeSinglePipeMetaChanges(PipeTaskAgent.java:275)
        at org.apache.iotdb.db.pipe.agent.task.PipeTaskAgent.handlePipeMetaChangesInternal(PipeTaskAgent.java:210)
        at org.apache.iotdb.db.pipe.agent.task.PipeTaskAgent.handlePipeMetaChanges(PipeTaskAgent.java:191)
        at org.apache.iotdb.db.protocol.thrift.impl.DataNodeInternalRPCServiceImpl.pushPipeMeta(DataNodeInternalRPCServiceImpl.java:943)
        at org.apache.iotdb.mpp.rpc.thrift.IDataNodeRPCService$Processor$pushPipeMeta.getResult(IDataNodeRPCService.java:5746)
        at org.apache.iotdb.mpp.rpc.thrift.IDataNodeRPCService$Processor$pushPipeMeta.getResult(IDataNodeRPCService.java:5726)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.iotdb.pipe.api.exception.PipeParameterNotValidException: IoTDBThriftAsyncConnector does not support SSL transmission currently
        at org.apache.iotdb.pipe.api.customizer.parameter.PipeParameterValidator.validate(PipeParameterValidator.java:93)
        at org.apache.iotdb.db.pipe.connector.protocol.thrift.async.IoTDBThriftAsyncConnector.validate(IoTDBThriftAsyncConnector.java:122)
        at org.apache.iotdb.db.pipe.task.subtask.connector.PipeConnectorSubtaskManager.register(PipeConnectorSubtaskManager.java:99)
        ... 16 common frames omitted
```